---
- name: Setup grafana
  hosts: grafana
  become: yes

  roles:
    - role: prometheus
    - role: cloudalchemy.grafana
    # - role: node-exporter
  vars:
    agent_binary_location: /usr/local/bin      # Example /usr/local/bin
    agent_config_location: /etc/grafana-cloud      # Example /etc/grafana-cloud
    linux_architecture: amd64            # Example linux-amd64
    agent_config_local_path: linux-agent-config.yml  # Example linux-agent-config.yml
    agent_version: 0.32.1
    grafana_security:
      admin_user: admin
      admin_password: admin
    grafana_datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: "http://localhost:9090"
        is_default: true
