---
- name: Preflight
  ansible.builtin.include_tasks: preflight.yml
  tags:
    - prometheus_configure
    - prometheus_install
    - prometheus_run

- name: Install
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      become: true
  tags:
    - prometheus_install

- name: Configure
  ansible.builtin.include_tasks:
    file: configure.yml
    apply:
      become: true
  tags:
    - prometheus_configure

- name: Ensure prometheus service is started and enabled
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: prometheus
    state: started
    enabled: true
  tags:
    - prometheus_run
