---
# https://github.com/prometheus-community/ansible/blob/main/roles/node_exporter/tasks/preflight.yml
- name: Preflight
  ansible.builtin.include_tasks: preflight.yml
  tags:
    - ansible_exporter_install
    - ansible_exporter_configure
    - ansible_exporter_run

- name: Install
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      become: true
  when:
    ( not __node_exporter_is_installed.stat.exists ) or
    ( (__node_exporter_current_version_output.stderr_lines | length > 0)
      and (__node_exporter_current_version_output.stderr_lines[0].split(" ")[2] != node_exporter_version) ) or
    ( (__node_exporter_current_version_output.stdout_lines | length > 0)
      and (__node_exporter_current_version_output.stdout_lines[0].split(" ")[2] != node_exporter_version) ) or
    ( node_exporter_binary_local_dir | length > 0 )
  tags:
    - node_exporter_install

- name: Configure
  ansible.builtin.include_tasks:
    file: configure.yml
    apply:
      become: True
  tags:
    - node_exporter_configure

- name: Ensure Node Exporter is enabled on boot
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: node_exporter
    enabled: true
    state: started
  when:
    - not ansible_check_mode
  tags:
    - node_exporter_run